### PR TITLE
Updated libpng and zlib libraries with pr fixes to address memory leaks.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Skycoder42** [comment]
I will keep this open until I fixed the CI. I will merge it, as soon as I can verify it still works with the updated versions

**Comment by Skycoder42** [comment]
Please rebase your commit to the latest master branch

**Comment by Skycoder42** [comment]
I rebased your initial commit to master on the "pr/pr-9" branch to get a clean commit history and because my CI is not configured correctly yet. If the [CI](https://github.com/Skycoder42/QtApng/actions/runs/46875233) succeeds, I will merge that one instead and simply close this PR. Sorry for the inconvenience...

**Comment by ghost** [comment]
Hey no problem whatsoever. Sorry for not responding sooner. I'm glad I was able to help. looks like the ci itself built successfully.

**Comment by ghost** [comment]
As a side note the PR fixes also include those after 1.6.37 were released that were not present in that version.

**Comment by Skycoder42** [comment]
Okay - I updated to 1.6.37 myself now, but I would like to wait with 1.38 until it actually gets released.

Where do you get that information from (the fixes in 38) - as far as I can see, the issue seems to be fixed in 1.6.37

**Pull request closed without merging**
